### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by lesv**
* One security issue is fixed in this PR.
* TODO(): Need to verify javac.version and if errorprone is running correctly for both J8 and J11
* Remove Jisha & Tim

### CODE REVIEW

**Comment by lesv** [comment]
I apparently need to test this more.  Not sure why the install of Java 8 is no longer working.  Looks like the kokoro build needs work.

TODO has been done - it should just work.

**Comment by lesv** [comment]
@kurtisvg PTAL I updated .travis to use bionic; and stop attempting to use OracleJDK8, it defaults to OpenJDK11.

**Comment by lesv** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.401 s
[INFO] Finished at: 2020-03-05T17:15:20Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check (default) on project shared-configuration: Failed during checkstyle configuration: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The command "mvn clean verify && cd test && mvn clean verify" exited with 1.
```

**Comment by kurtisvg** [comment]
@lesv - Looks like this is a change in [checkstyle as of 8.26](https://github.com/checkstyle/eclipse-cs/issues/190). We probably need to update the `google_checks.xml` in the[ third_party folder from the source. ](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)

**Comment by lesv** [comment]
@kurtisvg PTAL

**Comment by lesv** [comment]
```
[ERROR] /home/travis/build/GoogleCloudPlatform/java-repo-tools/test/src/test/java/com/google/cloud/samples/test/AppTest.java:24: Extra separation in import group before 'org.junit.Test' [CustomImportOrder]
Audit done.
[INFO] There is 1 error reported by Checkstyle 8.30 with google-checks.xml ruleset.
[ERROR] src/test/java/com/google/cloud/samples/test/AppTest.java:[24] (imports) CustomImportOrder: Extra separation in import group before 'org.junit.Test'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.117 s
[INFO] Finished at: 2020-03-05T18:26:46Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check (default) on project shared-configuration-test: You have 1 Checkstyle violation. -> [Help 1]

```

**Pull request merged**
