### PR TITLE
Move checkstyle configs to its own resources package.

### PR DESCRIPTION
**Pull request by tswast**
The checkstyle config can read from the resources of a package. It can't
read from the resources of the package it is included in, though (plus
you can't use a jar as a parent, anyway).

See: http://stackoverflow.com/a/19690484/101923

@lesv This should prevent us from having to duplicate these resources in all our repos.

Fixes https://github.com/GoogleCloudPlatform/java-repo-tools/issues/41

### CODE REVIEW

**Comment by tswast** [comment]
Travis failure was because I forgot to `mvn deploy` the SNAPSHOT version of the checkstyle-configuration jar.

**Comment by tswast** [comment]
Force merging so I can make a release with this. I've tested with the snapshot version locally on java-docs-samples.

@lesv PTAL

**Comment by lesv** [comment]
Cool - I was about to ask you about this as I wanted to put it in the Bookshelf.

**Comment by lesv** [comment]
The only comment I have is that the snapshot should be after the release, and you should have a protocol for release.

I.E.:
1. Commit all changes, test.
2. update& commit the version for release from x.x.x-SNAPSHOT to x.x.x
3. push to maven central
4. update & commit the version for release to x.x.y-SNAPSHOT

**Comment by tswast** [comment]
Yes, that protocol is basically what the Maven releases plugin does.
http://maven.apache.org/maven-release/maven-release-plugin/index.html

I'll be sure to document the steps when I make the next release.

**Pull request merged**
